global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'streaming-platform'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics

  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9092']

  - job_name: 'spark'
    static_configs:
      - targets: ['host.docker.internal:4040']
